language: php

branches:
  only:
    - master

php:
  - 7.0

env:
  - SYMFONY_VERSION=2.8.*

install:
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist

script:
  - phpunit

matrix:
  include:
    - php: 5.3
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: hhvm
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=dev-master
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
